const ADD_FAVOURITE = "ADD_FAVOURITE";
const RESET_FAVOURITE="RESET_FAVOURITE"
const DELETE_FAVOURITE="DELETE_FAVOURITE"
const ADD_VALUES= "ADD_VALUES"
export default {
  ADD_FAVOURITE,
  RESET_FAVOURITE,
  DELETE_FAVOURITE,
  ADD_VALUES
};
